### PR TITLE
Fix error with Yarn Workspaces

### LINKED ISSUE #509: Error when pushing yarn application with workspaces object in package.json
## What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
❯ cf -v
cf version 8.0.0+a4ae5d18d.2022-09-28
```

```
❯ cf curl / | jq .links.cloud_controller_v3.meta.version
"3.126.0"
```

## What version of the buildpack you are using?

`v1.8.0`

## If you were attempting to accomplish a task, what was it you were attempting to do?

I was attempting to push [Backstage](https://github.com/backstage/backstage).

Backstage, a yarn application, has an object for the `workspaces` key in its `package.json`, instead of the more standard array:
https://github.com/backstage/backstage/blob/44aa394c354a9166c90e53b9de7cf739a23739f8/package.json#L37-L42

This is supported by yarn, as is documented in this article: https://classic.yarnpkg.com/blog/2018/02/15/nohoist/

Here is an example of another issue caused by object `workspaces`: https://github.com/microsoft/vscode/issues/77912

##  What did you expect to happen?

The app to push successfully.

## What was the actual behavior?

```
   2022-09-28T15:02:12.75-0700 [API/1] OUT Creating build for app with guid 1101d19d-6131-4176-9696-0f1990a4e3a8
   2022-09-28T15:02:13.14-0700 [STG/0] OUT Downloading nodejs_buildpack...
   2022-09-28T15:02:13.15-0700 [STG/0] OUT Downloaded nodejs_buildpack
   2022-09-28T15:02:13.15-0700 [STG/0] OUT Cell ec6d2362-1aeb-43a6-93c5-10d0fab7717f creating container for instance ab37fa73-45ae-4d70-ba38-4e99573eee8c
   2022-09-28T15:02:13.72-0700 [STG/0] OUT Cell ec6d2362-1aeb-43a6-93c5-10d0fab7717f successfully created container for instance ab37fa73-45ae-4d70-ba38-4e99573eee8c
   2022-09-28T15:02:14.59-0700 [STG/0] OUT Downloading app package...
   2022-09-28T15:02:14.59-0700 [STG/0] OUT Downloading build artifacts cache...
   2022-09-28T15:02:33.47-0700 [STG/0] OUT Downloaded app package (228.7M)
   2022-09-28T15:02:57.67-0700 [STG/0] OUT Downloaded build artifacts cache (190.7M)
   2022-09-28T15:02:58.03-0700 [STG/0] OUT -----> Nodejs Buildpack version 1.8.0
   2022-09-28T15:02:58.03-0700 [STG/0] OUT **WARNING** buildpack version changed from 1.7.69 to 1.8.0
   2022-09-28T15:02:59.72-0700 [STG/0] OUT -----> Installing binaries
   2022-09-28T15:02:59.72-0700 [STG/0] OUT engines.node (package.json): 14 || 16
   2022-09-28T15:02:59.72-0700 [STG/0] OUT engines.npm (package.json): unspecified (use default)
   2022-09-28T15:02:59.72-0700 [STG/0] OUT -----> Installing node 16.17.0
   2022-09-28T15:02:59.72-0700 [STG/0] OUT Copy [/tmp/buildpacks/faefd3716540ed011a38971545e12047/dependencies/ed71407b9c40b957554783e91664163f/node_16.17.0_linux_x64_cflinuxfs3_d92abdd8.tgz]
   2022-09-28T15:03:02.69-0700 [STG/0] OUT Using default npm version: 8.15.0
   2022-09-28T15:03:02.69-0700 [STG/0] OUT -----> Installing yarn 1.22.19
   2022-09-28T15:03:02.69-0700 [STG/0] OUT Copy [/tmp/buildpacks/faefd3716540ed011a38971545e12047/dependencies/0f06052381cbcef1593bd279ca3d9458/yarn_1.22.19_linux_noarch_any-stack_32d0e82e.tgz]
   2022-09-28T15:03:03.21-0700 [STG/0] OUT Installed yarn 1.22.19
   2022-09-28T15:03:03.21-0700 [STG/0] OUT -----> Creating runtime environment
   2022-09-28T15:03:03.21-0700 [STG/0] OUT **ERROR** Failed parsing package.json: json: cannot unmarshal object into Go struct field .workspaces of type []string
   2022-09-28T15:03:03.38-0700 [STG/0] ERR Failed to compile droplet: Failed to run all supply scripts: exit status 14
   2022-09-28T15:03:03.40-0700 [STG/0] OUT Exit status 223
   2022-09-28T15:03:03.85-0700 [STG/0] OUT Cell ec6d2362-1aeb-43a6-93c5-10d0fab7717f stopping instance ab37fa73-45ae-4d70-ba38-4e99573eee8c
   2022-09-28T15:03:03.85-0700 [STG/0] OUT Cell ec6d2362-1aeb-43a6-93c5-10d0fab7717f destroying container for instance ab37fa73-45ae-4d70-ba38-4e99573eee8c
   2022-09-28T15:03:03.91-0700 [API/1] ERR Failed to stage build: staging failed
   2022-09-28T15:03:16.57-0700 [STG/0] OUT Cell ec6d2362-1aeb-43a6-93c5-10d0fab7717f successfully destroyed container for instance ab37fa73-45ae-4d70-ba38-4e99573eee8c
```

Key Error: `**ERROR** Failed parsing package.json: json: cannot unmarshal object into Go struct field .workspaces of type []string`

After hitting this issue, I swapped the object to be an array, and it pushed successfully:
```
❯ cat package.json | jq '.workspaces = .workspaces.packages' | sponge package.json
```

## Can you provide a sample app?

Modifying any Node application's package.json will reproduce this issue.

## Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

### PR DESCRIPTION
**Pull request by brayanhenao**
Fixes #509

### CODE REVIEW

**Comment by ryanmoran** [comment]
Does this still support the existing array declaration?

**Comment by brayanhenao** [comment]
> Does this still support the existing array declaration?

Do yarn support both declarations?

The logic that I introduce in the code is basically if Yarn is used, then the struct change to allow JSON Object in workspaces. if not, then it uses the normal JSON Array for workspaces.

**Comment by ryanmoran** [comment]
I'm just looking at [these docs](https://classic.yarnpkg.com/lang/en/docs/workspaces/) and it shows an array like what was previously supported.

**Comment by brayanhenao** [comment]
@Gerg Any comment on these? Since you initially open the Issue could you provide more info?

**Comment by Gerg** [comment]
Looks like both formats are accepted:
> Note: for those who don’t need nohoist, the old workspaces format will continue to be supported.
[Source](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/)

**Comment by brayanhenao** [comment]
@Gerg Looks like that is a blog post from `2018`. The live docs show the usage of `workspaces` with an Array.

**Comment by Gerg** [comment]
There is a link in the [Limitations & Caveats](https://classic.yarnpkg.com/lang/en/docs/workspaces/#toc-limitations-caveats) section of the live docs to the blog post.

Here is a machine-parsable schema for the field: https://github.com/zifahm/schemastore/blob/47f3be93df475483c683e64f7bc98cbae242e5fd/src/schemas/json/package.json#L427-L453

**Comment by brayanhenao** [comment]
@ryanmoran I updated the code to allow both types of formats.

@Gerg Could you try to push the app again referencing the Buildpack with:

```
cf push test-app -b https://github.com/brayanhenao/nodejs-buildpack
```

And let me know if it works

**Comment by Gerg** [comment]
@brayanhenao Worked great. Thanks!

**Pull request merged**
