### PR TITLE
Fix small typo in link to CF buildpack docs

### PR DESCRIPTION
**Pull request by kevinSuttle**
"Clou**n**dFoundry" vs "CloudFoundry"

### CODE REVIEW

**Comment by flavorjones** [comment]
LGTM.

**Comment by crawsible** [comment]
Hey there @kevinSuttle, thanks for the PR! Can you re-submit this to our repo's `develop` branch instead of `master`, as per our [contribution guidelines](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/CONTRIBUTING.md)? Once you do, we'll be happy to merge it in.

Thanks again, and thanks for using Cloud Foundry!

**Comment by kevinSuttle** [comment]
@crawsible Will do. I will also complete the appropriate CLA process. Thank you.

**Comment by kevinSuttle** [comment]
@crawsible CLA signed and approved. PR opened against `develop` branch. https://github.com/cloudfoundry/nodejs-buildpack/pull/26

**Pull request closed without merging**
