### PR TITLE
Add information about running integration tests

### PR DESCRIPTION
**Pull request by TimGerlach**
Add information about the prerequisites that are required for running integration-tests to reduce the onboarding time of new contributors.

Just a proposal - feel free to modify :)

### CODE REVIEW

**Comment by dgodd** [comment]
@TimGerlach I like it. Just pulling in a few more people.

@sclevine @idoru I think we should accept this and copy to the other buildpacks (excepting the pcfdev link). Thoughts?

**Comment by idoru** [comment]
@TimGerlach Very good, thank you!

@dgodd I agree about the copying, this is universally useful.

**Comment by sclevine** [comment]
Thanks, prioritizing

**Comment by TimGerlach** [comment]
Thanks all for merging.

@dgodd, I see you had to create a merge commit to resolve conflicts. Did you remove the last sentence about PCF Dev from my PR on purpose or did this happen accidentally?

**Comment by dgodd** [comment]
@TimGerlach it was intentional. The buildpacks are opensource and PCFDEV is not

**Pull request merged**
