### PR TITLE
Correct the feature flag and Override App, Tier, Node names only when required

### PR DESCRIPTION
**Pull request by pavankrish123**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

A short explanation of the proposed change:

1. The Feature flag that guards the logic against double configuration when multibuildpack is used is APPD_AGENT not APPD_BUILDPACK - Changed it to use correct flag
2. App/Tier/Node names can be overridden by setting environment variables. Honor those environment variables when they are passed explicitly passed via app manifest. Only set if they are not provided.

An explanation of the use cases your change solves

 *[X] I have viewed signed and have submitted the Contributor License Agreement

 *[X] I have made this pull request to the develop branch

*[X] I have added an integration test

### CODE REVIEW

**Comment by pavankrish123** [comment]
Hi, AppDynamics has signed the new Easy CLA. Please let us know if you need anything else

**Comment by dfreilich** [comment]
@pavankrish123 Would you be able to click on the link to make sure the CLA is fully completed? It looks like some commits were on an account that isn't yet covered under the CLA. Once you do that, we can move ahead with this.

**Comment by pavankrish123** [comment]
Thanks @dfreilich . I clicked the link and git the confirmation. Kindly let me know if  there are any further steps. 

Screen Shot 2019-11-27 at 12 31 04 PM

**Comment by dwillist** [comment]
@pavankrish123 Thanks! We'll be prioritizing this merge soon!

**Comment by pavankrish123** [comment]
Thanks a ton @dwillist.

**Comment by pavankrish123** [comment]
Hi @dwillist, Kindly let us know when can we expect this in an official buildpack release?

**Pull request merged**
