### PR TITLE
Changes Specific to AppDynamics to Nodejs BP

### PR DESCRIPTION
**Pull request by pkumar-appd**
Pull Request contains changes to make BP work with Appdynamics and get application monitored on Appdyanmics Controller.

### CODE REVIEW

**Comment by jtarchie** [comment]
@pkumar-appd, our [contributing](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/CONTRIBUTING.md) guidelines specify that pull requests should be done against the `develop` branch. Please open a new PR with these commits on `develop`.  Thanks.

Some notes about the PR code:

1. Since this is a public facing buildpack, we'd like to make sure that all features are working correctly with it. We'd like to have test coverage that ensures that this feature is always up to date and working.
2. It will not support air-gapped, which some users of Cloud Foundry are using. This [line](https://github.com/cloudfoundry/nodejs-buildpack/pull/49/files#diff-fa848a8feab190fd571242cf9fc568ecR74) will try and call out to the public internet.
3. It looks like debug statements were left in the code, such as `npm root` and `npm list`. This will just be unneeded during a normal staging process.
4. You are writing the environment variables `VCAP_SERVICES` and `VCAP_APPLICATION` to files. We discourage this practice because these artifacts could be a security concern.

**Comment by pkumar-appd** [comment]
@jtarchie 
Thanks for list down the changes needed. 
I have few queries related to point 2 and 4.

I need to install appdynamics packages. And to do that i am running "npm install appdynamics". Seems the Buildpack needs to work without public internet. So is there any other way to get the packages installed.

About point 4.
Right i am storing VCAP_SERVICES and VCAP_APPLICATION to files. But these files are in /tmp directory. so i assumed that once application gets deployed successfully the files will not longer exist.

**Comment by flavorjones** [comment]
I'm OK with writing sensitive data to a file in `/tmp` if necessary, as that directory is not included as part of the droplet. In this case, though, I don't think it's necessary.

I think it would be more secure to examine the environment variables from within `extensions/appdynamics/extension_appdy.py`, which has the side benefits of being simpler and easier to read.

**Comment by jvshahid** [comment]
According to this [line](https://github.com/cloudfoundry/nodejs-buildpack/pull/49/files#diff-b796d034e8c512aaeb727f89e3598620R54), it looks like the content of `VCAP_APPLICATION` is being copied into the `build_dir`. This means the content of `VCAP_APPLICATION` is packaged in the droplet.

**Comment by pkumar-appd** [comment]
@jvshahid Right as i need them to be used in the start, before server.js file gets executed. Is there any other way to execute the statement without writing into a file.

**Comment by nkatre** [comment]
The CLA is submitted to CF org. Copying @chipchilders for confirmation

Copying @akankshudhawan

**Comment by chipchilders** [comment]
@nkatre is correct. AppD has submitted an appropriate CLA. cc/ @flavorjones

**Comment by flavorjones** [comment]
@pkumar-appd It would be great if you could publicize your membership in the `appdynamics` github org, so that future PRs won't be flagged by dreddbot. (Instructions are above, in cfdreddbot's comment).

**Comment by pkumar-appd** [comment]
@jtarchie @jvshahid I am no longer copying content of VCAP_SERVICES and VCAP_APPLICATION into /tmp directory. Dealing with environment variables directly instead of actual values.

but in the PR i can see one of the test failing with reason.

NameError:
       undefined local variable or method `dockerfile_output' for #<RSpec::Matchers::DSL::Matcher have_internet_traffic>

Can you please check as i am not dealing with this variable or method in the code.

**Comment by jtarchie** [comment]
@pkumar-appd, I believe this is happening because your fork is on a previously broken build, that issue is does not appear to be related to you.

Are you able to address the previous points, though?

1. Since this is a public facing buildpack, we'd like to make sure that all features are working correctly with it. We'd like to have test coverage that ensures that this feature is always up to date and working.
1. It will not support air-gapped, which some users of Cloud Foundry are using. This line will try and call out to the public internet.

**Comment by nkatre** [comment]
@pkumar-appd Can you pull in the latest code from master repo. Merge those changes and try again

**Comment by pkumar-appd** [comment]
As all checks have passed. We can get it merged now.

**Comment by pkumar-appd** [comment]
@jtarchie if there is not blocker can we have this PR merged.

**Comment by flavorjones** [comment]
I hope you understand that we're holding off on merging any AppDynamics-related code until the open questions around redistribution of the agent have been resolved between the Foundation and AppDynamics.

I've been on a few calls with AppD legal and the Foundation leadership, and I'm hopeful we'll have resolution on this in the near future.

**Comment by akankshudhawan** [comment]
@flavorjones Since we have resolved the redistribution issue, can we go ahead and merge this PR request? FYI @chipchilders @nebhale

**Comment by flavorjones** [comment]
@akankshudhawan Hi, thanks for asking.

There are actually quite a few things that need to be put into place before we can merge this PR and ship it in a buildpack related to US export compliance regulations.

I've got a "to-do" to write everything up, but the high-level summary is:

* stop publishing cached buildpacks to github releases
* publish all buildpacks to a central S3 bucket
* put the S3 bucket behind a CDN that allows us to enforce export compliance regulations
* announce to cf-dev that this is the plan far enough in advance to allow people to update any automated processes that rely on downloading cached buildpacks from github releases (assume at least 30 days)

In addition to those global process changes, there are very specific things about this pull request that need to be addressed:

* on March 3 and March 15, @jtarchie asked @pkumar-appd  to provide test coverage to ensure that AppD support will always work as expected.
* on March 3, @jtarchie asked @pkumar-appd to rebase this pull request onto the `develop` branch as specified in our [contributor guidelines](https://github.com/cloudfoundry/nodejs-buildpack/blob/master/CONTRIBUTING.md).

Please address these issues, and in parallel we'll start down the path of updating our distribution model to allow for export compliance regulation.

**Comment by jchesterpivotal** [comment]
Hi @pkumar-appd, here are our notes from reviewing the latest commit (21d1754f06a7f0b6c674595e06a6ebea29dc3c22) to this PR.

1. As with the original commit for this PR, we see no test coverage. The buildpacks team commit to covering, at least to a feature-test level, code that is added to the buildpack. This rule is applied equally to code we write and code we accept by PR.
1. We appreciate that this patch used Python more directly, rather than leaning heavily on bash scripting. We were concerned by the use of [nested template code](https://github.com/cloudfoundry/nodejs-buildpack/pull/49/commits/21d1754f06a7f0b6c674595e06a6ebea29dc3c22#diff-c32190a8082e767b4458d382dde08883R30), which is difficult to reason about and difficult to test. We note also that this Python code is not unit tested.
1. [Inline Python is even hard to reason about.](https://github.com/cloudfoundry/nodejs-buildpack/pull/49/commits/21d1754f06a7f0b6c674595e06a6ebea29dc3c22#diff-c32190a8082e767b4458d382dde08883R30). If you need to manipulate json in bash, use `jq`, which is included in the rootfs for this purpose.
1. Where possible, we try to avoid sprinkling vendor-specific blocks of code across the core scripts (`detect`, `compile` and `release`). Ideally, all logic will be kept in vendor-specific files, referred to from a single line in one of those scripts. For example [the New Relic implementation in NodeJS](https://github.com/cloudfoundry/nodejs-buildpack/blob/develop/bin/compile#L41) respects this pattern.
1. [These lines can't be accepted](https://github.com/Appdynamics/nodejs-buildpack/blob/21d1754f06a7f0b6c674595e06a6ebea29dc3c22/manifest.yml#L60-L65). We cannot use Heroku binaries and it is a security risk to use a very old version that will not be updated by our tools. We're also not sure what purpose this copy of Node serves.

The issues mentioned by @flavorjones are still outstanding.

**Comment by RochesterinNYC** [comment]
@pkumar-appd thoughts on @jchesterpivotal's comments?

**Comment by sesmith177** [comment]
@pkumar-appd thoughts on @jchesterpivotal's comments?

**Comment by pkumar-appd** [comment]
@sesmith177 @RochesterinNYC working on changes. Changes being done are:
Adding install.sh for appdynamics, this script will be called in compile file at load dependencies.
Install.sh will use VCAP_SERVICE and VCAP_APPLICATION and create appdynamics-setup.sh  under .profile.d
appdynamics-setup.sh will mainly export environment variables to be used by appdynamics agent.
Adding tests for the code coverage.

**Comment by pkumar-appd** [comment]
@sesmith177 i have submitted changes to add support for Appdynamics. Please Review

**Comment by jchesterpivotal** [comment]
Hi @pkumar-appd, we appreciate that you added the unit test. However, it looks as though this PR has lost some of the earlier commits (eg https://github.com/cloudfoundry/nodejs-buildpack/commit/21d1754f06a7f0b6c674595e06a6ebea29dc3c22).

The dates for both commits are Feb 17 -- perhaps you accidentally amended the original? It's hard to tell.

However, as it stands now, this PR wouldn't work, as its missing some of the previous changes you'd queued up.

**Comment by pkumar-appd** [comment]
Hi @jchesterpivotal yes those commits will not be done any more on the Buildpack side. As per the last comments you provided, i am not updating any of the core scripts now. Instead added a new file that gets sourced.

Do you want me to raise new PR with these changes?

**Comment by RochesterinNYC** [comment]
@pkumar-appd where is the appdynamics agent? I don't see anywhere in the code for this PR that installs, loads, or starts the appdynamics agent, just functionality to setup the appropriate environment variables. How does this PR function without the agent?

Thanks for your clarifications.

**Comment by pkumar-appd** [comment]
@RochesterinNYC 
To get Appdynamics Agent binaries user needs to provide appdynamics entry along with version in package.json (present as a part of application) file under dependency section.
Once appdynamics entry provided in json file. The buildpack while downloading other dependencies will also download appdynamics dependencies.

**Comment by RochesterinNYC** [comment]
@pkumar-appd does that mean the app is able to get and install the AppDynamics agent purely as a node module?

**Comment by nkatre** [comment]
Yes, the appdynamics agent binaries are downloaded through npm. We basically cannot change this workflow as this is the way how we host our agent binaries.
@RochesterinNYC Let me know if you have additional questions regarding the same.

**Comment by sesmith177** [comment]
@nkatre @pkumar-appd It looks like your unit specs do not run correctly:

```
cf_exec rspec cf_spec/unit/appdynamics_install_spec.rb
/Users/pivotal/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `load': /private/tmp/appdynamics/nodejs-buildpack/cf_spec/unit/appdynamics_install_spec.rb:54: syntax error, unexpected tSTRING_BEG, expecting '}' (SyntaxError)
              "port": "1234"
               ^
/private/tmp/appdynamics/nodejs-buildpack/cf_spec/unit/appdynamics_install_spec.rb:54: syntax error, unexpected ':', expecting '}'
              "port": "1234"
                     ^
/private/tmp/appdynamics/nodejs-buildpack/cf_spec/unit/appdynamics_install_spec.rb:55: syntax error, unexpected ':', expecting '}'
              "account-name": "test-customer"
                             ^
/private/tmp/appdynamics/nodejs-buildpack/cf_spec/unit/appdynamics_install_spec.rb:56: syntax error, unexpected ':', expecting '}'
...          "account-access-key": "appdynamics_license_key_set...
...                               ^
/private/tmp/appdynamics/nodejs-buildpack/cf_spec/unit/appdynamics_install_spec.rb:58: syntax error, unexpected '}', expecting keyword_end
          }]
           ^
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `each'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:100:in `setup'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:86:in `run'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.1/exe/rspec:4:in `<top (required)>'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/bin/rspec:22:in `load'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/bin/rspec:22:in `<main>'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/pivotal/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sesmith177** [comment]
@pkumar-appd @nkatre The tests run now, but do not pass:

```
± |master ✓| → cf_exec rspec cf_spec/unit/appdynamics_install_spec.rb
...FF.F.

Failures:

  1) Appdynamics Installer vcap services contains appdynamics APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY set does not modify APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
     Failure/Error: expect(profile_d_contents).to_not include('APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY')
       expected "export APPDYNAMICS_CONTROLLER_HOST_NAME=test-host-name\nexport APPDYNAMICS_CONTROLLER_PORT=1234\nexp...xport APPDYNAMICS_AGENT_TIER_NAME=unit-test-app\nexport APPDYNAMICS_AGENT_NODE_NAME=unit-test-app\n" not to include "APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
     # ./cf_spec/unit/appdynamics_install_spec.rb:98:in `block (5 levels) in <top (required)>'

  2) Appdynamics Installer vcap services contains appdynamics APPDYNAMICS_AGENT_APPLICATION_NAME set does not modify APPDYNAMICS_AGENT_APPLICATION_NAME
     Failure/Error: expect(profile_d_contents).to_not include('APPDYNAMICS_AGENT_APPLICATION_NAME')
       expected "export APPDYNAMICS_CONTROLLER_HOST_NAME=test-host-name\nexport APPDYNAMICS_CONTROLLER_PORT=1234\nexp...xport APPDYNAMICS_AGENT_TIER_NAME=unit-test-app\nexport APPDYNAMICS_AGENT_NODE_NAME=unit-test-app\n" not to include "APPDYNAMICS_AGENT_APPLICATION_NAME"
     # ./cf_spec/unit/appdynamics_install_spec.rb:115:in `block (5 levels) in <top (required)>'

  3) Appdynamics Installer vcap services contains appdynamics APPDYNAMICS_AGENT_APPLICATION_NAME and APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY set does not create .profile.d/appdynamics-setup.sh file
     Failure/Error: expect(File.exist?(profile_d_appdynamics)).to be_falsey

       expected: falsey value
            got: true
     # ./cf_spec/unit/appdynamics_install_spec.rb:140:in `block (5 levels) in <top (required)>'

Finished in 0.32577 seconds (files took 0.07157 seconds to load)
8 examples, 3 failures

Failed examples:

rspec ./cf_spec/unit/appdynamics_install_spec.rb:94 # Appdynamics Installer vcap services contains appdynamics APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY set does not modify APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
rspec ./cf_spec/unit/appdynamics_install_spec.rb:111 # Appdynamics Installer vcap services contains appdynamics APPDYNAMICS_AGENT_APPLICATION_NAME set does not modify APPDYNAMICS_AGENT_APPLICATION_NAME
rspec ./cf_spec/unit/appdynamics_install_spec.rb:137 # Appdynamics Installer vcap services contains appdynamics APPDYNAMICS_AGENT_APPLICATION_NAME and APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY set does not create .profile.d/appdynamics-setup.sh file
```

**Comment by sesmith177** [comment]
@pkumar-appd @nkatre have you had a chance to fix the failing tests?

**Comment by pkumar-appd** [comment]
@sesmith177 sorry for the delay in response. I was also stuck with framework machete. Got it working also updated the PR. Verified tests and they are working now.
i am using rspec version 3.5.4

**Comment by dgodd** [comment]
@pkumar-appd Is there a reason for switching to a key of `user-provided` ( https://github.com/Appdynamics/nodejs-buildpack/blob/14ff41ea9c4e84b632ba83f7dda70a336ac2c29c/lib/vendor/appdynamics/install.sh#L17-L20 ). This seems problematic, and no tests exist for it.

**Comment by pkumar-appd** [comment]
@dgodd Key switch is needed as we are supporting CUPS service.
Service created from UI contains Appdynamics as the key. But CUPS service has user-provided as the key to the JSON Object. Regarding tests, will be adding few more tests regarding cups service.

**Comment by sesmith177** [comment]
@pkumar-appd At the moment install.sh checks the **first** `user-provided` if `appdynamics` is specified anywhere. Thus if there is a user provided DB, and also an `appdynamics` service, then the code will probably send appdynamics information to the DB endpoint.

**Comment by nkatre** [comment]
@sesmith177 The changes that you rightly mentioned are been made, can you please check the added commits ?

**Comment by nkatre** [comment]
@sesmith177 @dgodd  Any updated on this ?

**Comment by sclevine** [comment]
@nkatre This PR should be merged within a week. Please follow: https://www.pivotaltracker.com/story/show/143585835

**Comment by sclevine** [comment]
This PR is on `develop` and should be merged to `master` in the next release of the buildpack.

**Comment by nkatre** [comment]
Cool

**Comment by sclevine** [comment]
@nkatre @pkumar-appd Would you be willing to manually verify that the `develop` branch adds the functionality you expect?

(Alternatively, you could give me access to an environment with the AppDynamics tile that I can use for free.)

**Comment by sclevine** [comment]
@nkatre @pkumar-appd If you can't review the develop branch or give me access to an environment with the AppDynamics tile installed, we'll need to pull support out before the next release. Please let me know ASAP.

**Comment by nkatre** [comment]
I will test the develop branch today to check if its doing what is expected

**Comment by sclevine** [comment]
Awesome, thanks!

**Comment by sclevine** [comment]
@nkatre any updates here?

**Comment by nkatre** [comment]
This has been verified, works as expected :)

**Comment by nkatre** [comment]
There are some conflicts, let me look into this

**Comment by sclevine** [comment]
@nkatre No conflicts, this was merged and released! Github just failed to pick it up.

**Pull request closed without merging**
