### PR TITLE
SKP-13739 create prefix folder before calling npm install

### PR DESCRIPTION
**Pull request by hbarshak**
Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:
This patch is required to workaround a known issue in npm 7 (was fixed in 7.4).

* An explanation of the use cases your change solves
See: https://github.com/npm/cli/issues/2012

* [ ] I have viewed signed and have submitted the Contributor License Agreement

* [x] I have made this pull request to the `develop` branch

* [x] I have added an integration test

### CODE REVIEW

**Comment by fg-j** [comment]
Hey @hbarshak -- since it's a new calendar year, you'll need to re-sign the CLA even if you have signed it in the past. Please use the link in the EasyCLA bot comment above to get yourself authorized.

In the meantime, we'll review this code change 🙂

**Comment by fg-j** [comment]
@hbarshak With what version of the buildpack are you currently seeing the issue that requires this workaround? 

The known issue seems to have been fixed in npm v7.4.0, which [ships with node >= 15.6.0](https://nodejs.org/en/download/releases/). The most recent release of the buildpack [has node versions 15.9.0 and 15.10.0](https://github.com/cloudfoundry/nodejs-buildpack/blob/v1.7.44/manifest.yml#L90-L101), which should have an associated NPM version with the issue patched. 

As a result, we haven't been able to reproduce the issue this patch is fixing. We're wondering if a workaround is necessary given that the bugged version of NPM is no longer distributed in the buildpack.

**Comment by hbarshak** [comment]
@fg-j - the customer is using version v1.7.39.
node 15.4.0
npm version: 7.0.15

you're saying that upgrading to a newer version of the buildpack will fix their issue ?

**Comment by kvedurmu** [comment]
@hbarshak yes. As Frankie said, since the latest version of the buildpack has node versions 15.9.0 and 15.10.0, the associated NPM version (>7.4) will be included in the buildpack. 

Please have your customer upgrade to the latest version of the buildpack and let us know if it works. Buildpacks are technically only supported until a newer patch release of the buildpack comes out, due to the way dependencies are patched in upstream language families, so we should always encourage customers/end-users to upgrade to the latest buildpack version when they encounter an issue.

**Comment by hbarshak** [comment]
I've already asked them to upgrade.. waiting for their response.. but we can close this PR since i don't see any value in this fix.

**Pull request closed without merging**
