### PR TITLE
Bump version to 1.8.6

### PR DESCRIPTION
**Pull request by brayanhenao**

### CODE REVIEW

**Review by sophiewigmore — APPROVED** [review]

**Comment by sophiewigmore** [comment]
The tests won't run due to changes to the Test PR workflow which won't run on version bump changes, but this check is required. Someone who has access to remove that required check needs to remove it so we this PR can be merged.

**Comment by sophiewigmore** [comment]
Personally, I don't have the capability to merge this PR without the checks running so we're sort of stuck unless others can merge it. @ryanmoran should we disable the required checks, or should someone have the ability to just merge the PR without the checks running do you think?

**Comment by ryanmoran** [comment]
Resolving by removing this: https://github.com/cloudfoundry/nodejs-buildpack/pull/569. Its interesting how required workflows and exceptions to their triggering interact with one another. I guess I will have to take another approach to allowing release PRs to move through the PR process easier.

**Comment by sophiewigmore** [comment]
@ryanmoran yea, it seems very counterintuitive that it works that way. More of an issue on Github's side than how you set it up

**Pull request merged**
